[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ft_package"
version = "0.0.1"
description = "A sample test package"
readme = "README.md"
license = "MIT"
authors = [
  { name="", email="yzhuang@42.fr" }
]
requires-python = ">=3.7"